# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Resume-SwiftUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Resume-SwiftUI
  pod 'PromiseKit', '~> 6.8'
  pod 'SDWebImage', '~> 5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'Resume-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
